export const TABLE_INIT = 'TABLE_INIT';
export const TABLE_SET_COLUMNS = 'TABLE_SET_COLUMNS';
export const TABLE_SET_ROWS = 'TABLE_SET_ROWS';
export const TABLE_SET_GROUPS = 'TABLE_SET_GROUPS';
export const TABLE_SET_DISPLAYABLE_ROWS = 'TABLE_SET_DISPLAYABLE_ROWS';
export const TABLE_SORT = 'TABLE_SORT';
